apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer-api
  namespace: production
  labels:
    app: summarizer-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: summarizer-api
  template:
    metadata:
      labels:
        app: summarizer-api
    spec:
      containers:
      - name: summarizer-api
        image: ${ECR_REGISTRY}/summarizer-api:${IMAGE_TAG}
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: openai-api-key
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5