apiVersion: v1
kind: Service
metadata:
  name: summarizer-api-service
  namespace: production
spec:
  selector:
    app: summarizer-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer